### ISSUE TITLE
Starting electron fails

### ISSUE THREAD

**Issue by mixmixmix** [road86/bahis-desk#27]
After running `yarn install` on a windows machine
```
PS C:\Users\witol\bahis-desk> yarn electron .
yarn run v1.22.19
$ C:\Users\witol\bahis-desk\node_modules\.bin\electron .

App threw an error during load
Error: The module '\\?\C:\Users\witol\bahis-desk\node_modules\better-sqlite3\build\Release\better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing
the module (for instance, using npm rebuild or npm install).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\Users\witol\bahis-desk\node_modules\bindings\bindings.js:112:48)
    at new Database (C:\Users\witol\bahis-desk\node_modules\better-sqlite3\lib\database.js:48:64)
```

**Comment by mixmixmix** [comment]
The problem can be solved similarily to this: https://stackoverflow.com/a/52796884/4966367
`yarn add electron-rebuild`
`yarn electron-rebuild`
